### ISSUE TITLE
AWS: STS is not a constructor

### ISSUE THREAD

**Issue by joebernard** [EddyVerbruggen/nativescript-nodeify#32]
I'm building an Angular/NativeScript app that needs to interact with AWS Cognito. I'm getting an error from AWS that I think might be related to nativescript-nodeify. I only seem to have the issue with this plugin enabled. Running the same Angular code in a browser environment does not trigger the error.

I have the following service to authenticate a user based on a Facebook token:

```javascript
import { Injectable } from "@angular/core";
require("nativescript-nodeify");
import * as AWS from "aws-sdk/global";

@Injectable()
export class UserLoginService {

    authenticate(authToken: string){
        let creds = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: "xxxxxxxx",
            Logins: {"graph.facebook.com": authToken}
        });

        AWS.config.credentials = creds;

        creds.refresh((error) => {
            if (error) {
                console.error(error);
            } else {
                console.log('Successfully logged into Cognito!');
            }
        });
    }
}
```

Calling my `authenticate` function results in this AWS error: TypeError: STS is not a constructor

Stepping through it, `creds.refresh` attempts to set up the `STS` service [here](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/cognito_identity_credentials.js#L324). When I run this code in a browser (without nativescript-nodeify), this call is intercepted by another internal AWS function in util.js ([here](https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L586)) which handles the missing constructor issue. However, running on a device with nativescript-nodeify, the util.js function is never invoked, and it fails.

I found a reference to utils.js within [shims.json](https://github.com/EddyVerbruggen/nativescript-nodeify/blob/master/shims.json#L27) but I'm not sure if it is related. Deleting it did not fix the issue.

Since this seems to work in a browser, I'm wondering if nativescript-nodeify is interfering with that AWS `inherit` function and if there is a possible workaround. I appreciate any advisement!

**Comment by EddyVerbruggen** [comment]
Hi, thanks for the research on this one. I'd love to help you out but I require an app that I can clone and recreate this issue with a simple `tns run <platform>` so I'm sure I'm looking at the exact same issue (and dependency versions).

It would be perfect if you can share a minimal starter app that reproduces the issue, otherwise your app as-is would be fine too.

**Comment by joebernard** [comment]
Hi Eddy,

I created a demo app here:
https://github.com/joebernard/NS-AWS-TEST

There is a bit of a custom set up required:

Run `npm install`

Edit the `shims.json` file in the nodeify module, adding the following line: `"os": "nativescript-nodeify/empty.js"`. This seems to be required for the AWS SDK to function.

Then `tns run` the project.

Tap the INVOKE AWS button in the app and watch the console for the `STS` error.

**Comment by EddyVerbruggen** [comment]
Ha, thanks for those excellent details! I'll add a shim for `os` to the plugin (`os-browserify` seems to do the trick).

Regarding your issue: when I replace 

```json
    "nodeify": {
      "package-dependencies": {
        "aws-sdk": [
          {
            "xml/browser_parser": "xml/node_parser"
          }
        ]
      }
    },
```

by

```json
    "nodeify": {
      "package-dependencies": {
        "aws-sdk": [
          {
            "xml/browser_parser": "xml/node_parser",
            "lib/node_loader": "lib/browser_loader"
          }
        ]
      }
    },
```

I can get a little further. But since I don't have the correct AWS credentials setup in this project I'm getting this error in the `refresh` callback: "ConfigError: Missing region in config". I'd love to look into this further for you, but I'd need some credentials I guess (and I canceled my own AWS account a while ago). Can you give it a try and see if that moves things forward a little?

**Comment by joebernard** [comment]
Success! I'm able to get cognito working with that change. Thank you.

**Comment by karch4162** [comment]
Wasted a day trying to find a solution to this problem.  Finally stumbled across this thread, fixed me right up.  Nice work guys
